version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: figmaqa-backend
    env_file:
      - backend/.env
    environment:
      - FRONTEND_ORIGIN=http://localhost:5173
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
    container_name: figmaqa-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

networks:
  default:
    name: figmaqa-net

